title: Rauf Salamzade
description: Microbiology graduate student at UW Madison. test2

social-network-links:
  twitter: salamzader
  github:  raufs
  linkedin: rauf-salamzade-7992a534

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
