title: Your awesome title
author:
  name: Rauf Salamzade
description: > # this means to ignore newlines until "show_excerpts:"
  Microbiology graduate student at the UW Madison

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: salamzader
    github:  raufs
    # linkedin: salamzader

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
