theme: jekyll-theme-minimal

title: Rauf Salamzade
description: MDTP Graduate Student at UW Madison

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: https://twitter.com/salamzader
    github:  raufs
    linkedin: rauf-salamzade-7992a534

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
